import { useTranslations } from 'next-intl';
import Head from 'next/head';

import SubscribeForm from '../../../components/SubscribeForm';

export default function HomePage() {
  const t = useTranslations('Home');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          content="Generated by create next app"
          name="description"
        />
        <meta
          content="width=device-width, initial-scale=1"
          name="viewport"
        />
        {/* <link href="/favicon.ico" rel="icon" /> */}
      </Head>
      <article>
        <h1>{t('title')}</h1>
      </article>
      <SubscribeForm />
    </>
  );
}
